In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/goodreads-or-badreads/sample_submission.csv
/kaggle/input/goodreads-or-badreads/train.csv
/kaggle/input/goodreads-or-badreads/test.csv

In [2]:
import pandas as pd
import datetime as dt
df=pd.read_csv("/kaggle/input/goodreads-or-badreads/train.csv")
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,rating
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,3
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,5
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,4
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,5
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,5

In [3]:
from datetime import datetime

timestamp = "Tue Sep 12 17:14:59 -0700 2017"

# Convert string to datetime object
date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")

# Extract the day of the week
day_of_week = date_obj.strftime("%a")

print(day_of_week)

Tue

# Function to extract day of the week
def extract_day_of_week(timestamp):
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%a")

# Apply the function to the 'start_date' column
df['day_of_date_added'] = df['date_added'].apply(extract_day_of_week)

df.head()
# Function to extract day of the week
def extract_day_of_week(timestamp):
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%b")

# Apply the function to the 'start_date' column
df['month_of_date_added'] = df['date_added'].apply(extract_day_of_week)

df.head()

In [4]:
# List of desired columns to extract day of the week
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract day of the week
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%a")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_day_of_week'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,rating,date_added_day_of_week,read_at_day_of_week,date_updated_day_of_week,started_at_day_of_week
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,3,Tue,Mon,Tue,Sun
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,5,Sat,None,Fri,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,4,Tue,None,Sat,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,5,Thu,Sun,Thu,Thu
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,5,Wed,Mon,Mon,Sun

In [5]:
# List of desired columns to  extract month
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract month
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%b")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_month'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,rating,date_added_day_of_week,read_at_day_of_week,date_updated_day_of_week,started_at_day_of_week,date_added_month,read_at_month,date_updated_month,started_at_month
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,3,Tue,Mon,Tue,Sun,Sep,Sep,Sep,Jan
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,5,Sat,None,Fri,None,Mar,None,Mar,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,4,Tue,None,Sat,None,Oct,None,May,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,5,Thu,Sun,Thu,Thu,Sep,Sep,Feb,Sep
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,5,Wed,Mon,Mon,Sun,May,Mar,Mar,Mar

In [6]:
# List of desired columns to extract date
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract date
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%d")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_date'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_updated_day_of_week,started_at_day_of_week,date_added_month,read_at_month,date_updated_month,started_at_month,date_added_date,read_at_date,date_updated_date,started_at_date
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,...,Tue,Sun,Sep,Sep,Sep,Jan,12,11,12,01
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,Fri,None,Mar,None,Mar,None,14,None,27,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,Sat,None,Oct,None,May,None,23,None,18,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,...,Thu,Thu,Sep,Sep,Feb,Sep,03,06,18,03
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,...,Mon,Sun,May,Mar,Mar,Mar,30,18,18,17

In [7]:
# List of desired columns to extract date
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract time
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%H:%M:%S")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_time'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_updated_month,started_at_month,date_added_date,read_at_date,date_updated_date,started_at_date,date_added_time,read_at_time,date_updated_time,started_at_time
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,...,Sep,Jan,12,11,12,01,17:14:59,00:00:00,17:24:30,00:00:00
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,Mar,None,14,None,27,None,13:28:52,None,12:25:19,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,May,None,23,None,18,None,05:51:53,None,02:19:43,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,...,Feb,Sep,03,06,18,03,14:18:43,16:42:33,07:11:43,00:00:00
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,...,Mar,Mar,30,18,18,17,00:44:56,05:37:27,05:37:27,00:00:00

In [8]:
# List of desired columns to extract date
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract day of the week
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%z")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_zone'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_updated_date,started_at_date,date_added_time,read_at_time,date_updated_time,started_at_time,date_added_zone,read_at_zone,date_updated_zone,started_at_zone
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,...,12,01,17:14:59,00:00:00,17:24:30,00:00:00,-0700,-0700,-0700,-0800
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,27,None,13:28:52,None,12:25:19,None,-0700,None,-0700,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,18,None,05:51:53,None,02:19:43,None,-0700,None,-0700,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,...,18,03,14:18:43,16:42:33,07:11:43,00:00:00,-0700,-0700,-0800,-0700
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,...,18,17,00:44:56,05:37:27,05:37:27,00:00:00,-0700,-0700,-0700,-0700

In [9]:
# List of desired columns to extract date
desired_columns = ['date_added','read_at','date_updated','started_at']

# Function to extract day of the week
def extract_day_of_week(timestamp):
    if pd.isnull(timestamp):  # Check for NaN values
        return None
    date_obj = datetime.strptime(timestamp, "%a %b %d %H:%M:%S %z %Y")
    return date_obj.strftime("%Y")

# Apply the function to desired columns and create new columns
for column in desired_columns:
    df[f'{column}_year'] = df[column].apply(extract_day_of_week)
    
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_updated_time,started_at_time,date_added_zone,read_at_zone,date_updated_zone,started_at_zone,date_added_year,read_at_year,date_updated_year,started_at_year
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,...,17:24:30,00:00:00,-0700,-0700,-0700,-0800,2017,2017,2017,2017
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,12:25:19,None,-0700,None,-0700,None,2009,None,2009,None
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,02:19:43,None,-0700,None,-0700,None,2012,None,2013,None
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,...,07:11:43,00:00:00,-0700,-0700,-0800,-0700,2015,2015,2016,2015
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,...,05:37:27,00:00:00,-0700,-0700,-0700,-0700,2012,2013,2013,2013

In [10]:

df.shape
df.columns

Index(['user_id', 'book_id', 'review_id', 'review_text', 'date_added',
       'date_updated', 'read_at', 'started_at', 'n_votes', 'n_comments',
       'rating', 'date_added_day_of_week', 'read_at_day_of_week',
       'date_updated_day_of_week', 'started_at_day_of_week',
       'date_added_month', 'read_at_month', 'date_updated_month',
       'started_at_month', 'date_added_date', 'read_at_date',
       'date_updated_date', 'started_at_date', 'date_added_time',
       'read_at_time', 'date_updated_time', 'started_at_time',
       'date_added_zone', 'read_at_zone', 'date_updated_zone',
       'started_at_zone', 'date_added_year', 'read_at_year',
       'date_updated_year', 'started_at_year'],
      dtype='object')

In [11]:
df.isnull().sum()

user_id                          0
book_id                          0
review_id                        0
review_text                      0
date_added                       0
date_updated                     0
read_at                      64225
started_at                  192037
n_votes                          0
n_comments                       0
rating                           0
date_added_day_of_week           0
read_at_day_of_week          64225
date_updated_day_of_week         0
started_at_day_of_week      192037
date_added_month                 0
read_at_month                64225
date_updated_month               0
started_at_month            192037
date_added_date                  0
read_at_date                 64225
date_updated_date                0
started_at_date             192037
date_added_time                  0
read_at_time                 64225
date_updated_time                0
started_at_time             192037
date_added_zone                  0
read_at_zone                 64225
date_updated_zone                0
started_at_zone             192037
date_added_year                  0
read_at_year                 64225
date_updated_year                0
started_at_year             192037
dtype: int64

In [12]:
df.dtypes

user_id                     object
book_id                      int64
review_id                   object
review_text                 object
date_added                  object
date_updated                object
read_at                     object
started_at                  object
n_votes                      int64
n_comments                   int64
rating                       int64
date_added_day_of_week      object
read_at_day_of_week         object
date_updated_day_of_week    object
started_at_day_of_week      object
date_added_month            object
read_at_month               object
date_updated_month          object
started_at_month            object
date_added_date             object
read_at_date                object
date_updated_date           object
started_at_date             object
date_added_time             object
read_at_time                object
date_updated_time           object
started_at_time             object
date_added_zone             object
read_at_zone                object
date_updated_zone           object
started_at_zone             object
date_added_year             object
read_at_year                object
date_updated_year           object
started_at_year             object
dtype: object

In [13]:
import numpy as np
df['date_is_weekend']=np.where((df['date_added_day_of_week']).isin(['Sunday','Saturday']),1,0)
df['read_is_weekend']=np.where((df['read_at_day_of_week']).isin(['Sunday','Saturday']),1,0)
df['date_updated_is_weekend']=np.where((df['date_updated_day_of_week']).isin(['Sunday','Saturday']),1,0)
df['started_at_is_weekend']=np.where((df['started_at_day_of_week']).isin(['Sunday','Saturday']),1,0)
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_updated_zone,started_at_zone,date_added_year,read_at_year,date_updated_year,started_at_year,date_is_weekend,read_is_weekend,date_updated_is_weekend,started_at_is_weekend
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,"I ""read"" this as an audiobook. \n This book fo...",Tue Sep 12 17:14:59 -0700 2017,Tue Sep 12 17:24:30 -0700 2017,Mon Sep 11 00:00:00 -0700 2017,Sun Jan 01 00:00:00 -0800 2017,0,0,...,-0700,-0800,2017,2017,2017,2017,0,0,0,0
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,Easily one of the best sci-fi books out there ...,Sat Mar 14 13:28:52 -0700 2009,Fri Mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,-0700,None,2009,None,2009,None,0,0,0,0
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,Best. Sarah. Dessen. Book. Ever. And to anyone...,Tue Oct 23 05:51:53 -0700 2012,Sat May 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,-0700,None,2012,None,2013,None,0,0,0,0
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,"This series just gets better and better, and S...",Thu Sep 03 14:18:43 -0700 2015,Thu Feb 18 07:11:43 -0800 2016,Sun Sep 06 16:42:33 -0700 2015,Thu Sep 03 00:00:00 -0700 2015,0,0,...,-0800,-0700,2015,2015,2016,2015,0,0,0,0
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,For reviews on all the hottest to the underhyp...,Wed May 30 00:44:56 -0700 2012,Mon Mar 18 05:37:27 -0700 2013,Mon Mar 18 05:37:27 -0700 2013,Sun Mar 17 00:00:00 -0700 2013,0,0,...,-0700,-0700,2012,2013,2013,2013,0,0,0,0

In [14]:
object_columns = df.select_dtypes(include=['object']).columns
df[object_columns] = df[object_columns].apply(lambda x: x.str.lower())

In [15]:
df['review_text'][5533]

'i\'ve spent most of a day off wondering what to say about a brief history of seven killings as i have mixed feelings about this book. but i am still exhausted from making it through this book, so i don\'t want to write my own novel about it either. i\'ve compiled a list of things i liked and another list of things that weren\'t my cup of tea. \n things that worked well: \n 1. the audiobook is awesome. it\'s more of a radio play than narration, as multiple voice actors tackle different chapters, which follows the shifting narration of the book. because i listened to the audiobook, none of the patois was difficult to understand and it made the characters seem very authentic. i highly recommend this audiobook, but not if you\'re listening in a group that includes kids, as there is tons of coarse language, violence, sex, you name it, so, headphones are a must. \n 2.the various plots are separately intriguing. then when there is interactions between these seemingly distinct universes (world colliding!) it seemed almost incredible. we have the rival gangs, the media surrounding the singer, the government officials, the cia, and people who unfortunately ended up in the path of one or more of these groups. all of these universes are interesting, but some more than others. i just wished that there had either been more connection, or perhaps more editing / pruning (see below). \n 3. i loved the singer\'s spectral presence in the whole book (even in the 1990s in new york city, when he had been dead for a decade). he\'s always in back of the other characters\' subconscious (if not the front), even though he was never a chapter narrator, and we never got a contemporaneous account of any scene that he was in. this was an interesting approach, and it worked, as this book was around bob marley, not about him. \n 4. because of the character named shotta sheriff, i could not stop hearing the hook of the famous bob marley song, i shot the sheriff, over and over in my head. it\'s still there now, even though i\'m listening to the audiobook for the witches: salem, 1692. thanks for the earworm. i\'ve had worse. \n things that bugged me: \n 1.\tit\'s really long. too long. i don\'t need to speak at length about how long it is, do i? but as i\'d mentioned above, there were so many plots, and not all of them really tied together, so some pruning may have been in order. there were some very sloggy sections, particularly in the middle of the book that definitely could have been culled. i probably would have preferred about half of what happened in new york city. \n 2.\twho are these people again? listening to it on audiobook, i did not get the list of characters that was in the printed version. sometimes in audiobooks they will read these lists (case in point, the gospel of loki), but i\'m not sure that would have been all that helpful. i ended up looking at the printed copy to see it. this could have benefitted from the double media experience. which leads to another main gripe. \n 3.\tthis one is a spoiler. (view spoiler)[while i was reading, i couldn\'t tell for sure whether kim clarke, dorcas, and millicent were all nina burgess, or her sister kim, as she used the name kim in the second time frame. at the end, i concluded that they were all nina, but the use of the name kim clarke was confusing, as that was nina\'s sister kim-marie\'s name. why? just to make things extra confusing? you\'ve already got ghosts narrating chapters, you don\'t need to name a name shifting character something similar to her sister. in audiobook, this was unnecessarily misleading, as you don\'t have the character list at your fingertips. (hide spoiler)] \n 4. finally, the title itself is also misleading. we get an explanation of the title, but not until the fifth and final section. meanwhile once the death count gets to seven, we think we\'re home clear, but then bam, more killing. lots more killing. they hadn\'t even got started yet with the killing. and, at 700+ pages and hours upon hours of audiobook, "brief" is a cruel misnomer. we did eventually find out the source of the title, but i think the title was a poke at the readers. \n so overall, i liked it. i like reading books (even fiction) where i learn something. i felt that way in this book, but it isn\'t clear what aspects were fact versus fiction, so i\'m not sure if i actually did "learn" anything. the whole book seemed an embodiment of the old saying "those who live by the sword die by the sword." and, final spoiler (view spoiler)[it was unclear where heckle, the gang member who shot marley but earned his forgiveness, ended up. eubie indicated that he knew when talking to / tormenting alex pierce, and indicating that alex did also, so i guess that is implying heckle is eubie, but why don\'t people recognize him. or why bother bringing any of that up just to leave it as a loose thread, as it seemed rather pivotal, but had no satisfying conclusion. if they\'d said eubie had scars or something it would have made more sense, but instead he was some jamaican with no history with this gang, showing up in new york as the leader. just wha? yes, i was left thinking why bother will all that. waste of my damn time, because even if it was eubie, why bring it up? (hide spoiler)] it was interesting, but i thought it could have been a lot tighter, made more sense if there was less rambling, maybe a few of the more minor plots could have been scrapped. oh well, overall it was worth the read.'

In [16]:
import re
def remove(text):
    pattern=re.compile('\n')
    return pattern.sub(r'',text)
df['review_text']=df['review_text'].apply(remove)

In [17]:
df["review_text"] = df["review_text"].astype('str')
target_column = 'review_text'
df[target_column] = df[target_column].str.replace('\t', '', regex=False)

# Save the modified DataFrame back to a CSV file
df.to_csv('train.csv', index=False)

In [18]:
import string,time
string.punctuation
exclude=string.punctuation
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))
df['review_text']=df['review_text'].apply(remove_punc)

In [19]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
target_column = 'review_text'

# Set English stopwords from NLTK
stop_words = set(stopwords.words('english'))

# Function to remove stopwords
def remove_stopwords(text):
    text = ' '.join(word for word in text.split() if word.lower() not in stop_words)
    return text

# Remove stopwords from the specified column
df[target_column] = df[target_column].apply(remove_stopwords)

# Save the modified DataFrame back to a CSV file
df.to_csv('training.csv', index=False)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [20]:
from nltk.tokenize import word_tokenize

nltk.download('punkt')
target_column = 'review_text'
def tokenize(text):
    return word_tokenize(text)
df[target_column + '_tokens'] = df[target_column].apply(tokenize)

# Save the modified DataFrame back to CSV file
df.to_csv('training.csv', index=False)

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [21]:
df['review_text_tokens'][0]

['read',
 'audiobook',
 'book',
 'follows',
 'primarily',
 'jack',
 'private',
 'detective',
 'private',
 'get',
 'several',
 'characters',
 'including',
 'twin',
 'brother',
 'multiple',
 'love',
 'interests',
 'suspects',
 'coworkers',
 'light',
 'read',
 'mean',
 'wasnt',
 'horrible',
 'couldnt',
 'finish',
 'listening',
 'guess',
 'liked',
 'ok',
 'multiple',
 'plot',
 'lines',
 'dont',
 'relate',
 'way',
 'lots',
 'super',
 'cheesy',
 'dialogue',
 'despite',
 'couple',
 'mildly',
 'interesting',
 'subplots',
 'real',
 'suspense',
 'pick',
 'book',
 'want',
 'quickish',
 'read',
 'dont',
 'invest',
 'lot',
 'brainpower']

In [22]:
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["text_stemmed"] = df["review_text"].apply(lambda text: stem_words(text))
df.head()

,user_id,book_id,review_id,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments,...,date_added_year,read_at_year,date_updated_year,started_at_year,date_is_weekend,read_is_weekend,date_updated_is_weekend,started_at_is_weekend,review_text_tokens,text_stemmed
0,5845f85c23e768f0636c9c7f77f3a529,7134202,55d9037adc00645b17f0cf43fa4d053e,read audiobook book follows primarily jack pri...,tue sep 12 17:14:59 -0700 2017,tue sep 12 17:24:30 -0700 2017,mon sep 11 00:00:00 -0700 2017,sun jan 01 00:00:00 -0800 2017,0,0,...,2017,2017,2017,2017,0,0,0,0,"[read, audiobook, book, follows, primarily, ja...",read audiobook book follow primarili jack priv...
1,4251532f32b7e8b98912188f4d962eb1,2767052,e5f389a112b12d560e42e0c5c3d4eb35,easily one best scifi books kids didnt think s...,sat mar 14 13:28:52 -0700 2009,fri mar 27 12:25:19 -0700 2009,NaN,NaN,0,0,...,2009,None,2009,None,0,0,0,0,"[easily, one, best, scifi, books, kids, didnt,...",easili one best scifi book kid didnt think suz...
2,2cabd95f62285fc08f4c544afaee5ea4,8492856,e7892549ac69653aceaac86760575aa0,best sarah dessen book ever anyone says book s...,tue oct 23 05:51:53 -0700 2012,sat may 18 02:19:43 -0700 2013,NaN,NaN,0,0,...,2012,None,2013,None,0,0,0,0,"[best, sarah, dessen, book, ever, anyone, says...",best sarah dessen book ever anyon say book suc...
3,2d61d345434328a188f805ec75dde2c2,13206760,ab4acc9ad0a24a072356c331880b83d5,series gets better better scarlet didnt disapp...,thu sep 03 14:18:43 -0700 2015,thu feb 18 07:11:43 -0800 2016,sun sep 06 16:42:33 -0700 2015,thu sep 03 00:00:00 -0700 2015,0,0,...,2015,2015,2016,2015,0,0,0,0,"[series, gets, better, better, scarlet, didnt,...",seri get better better scarlet didnt disappoin...
4,a3e696e6ced8daae338eccf12ac58053,7171637,0b65c86a90814e4ab5db50e0cd3dc808,reviews hottest underhyped books ya lit enter ...,wed may 30 00:44:56 -0700 2012,mon mar 18 05:37:27 -0700 2013,mon mar 18 05:37:27 -0700 2013,sun mar 17 00:00:00 -0700 2013,0,0,...,2012,2013,2013,2013,0,0,0,0,"[reviews, hottest, underhyped, books, ya, lit,...",review hottest underhyp book ya lit enter chan...

In [23]:
df['text_stemmed'][0]

'read audiobook book follow primarili jack privat detect privat get sever charact includ twin brother multipl love interest suspect cowork light read mean wasnt horribl couldnt finish listen guess like ok multipl plot line dont relat way lot super cheesi dialogu despit coupl mildli interest subplot real suspens pick book want quickish read dont invest lot brainpow'